// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: caster/casting.proto

package caster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chromecast string `protobuf:"bytes,1,opt,name=chromecast,proto3" json:"chromecast,omitempty"`
	Stream     string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *CastStartRequest) Reset() {
	*x = CastStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caster_casting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastStartRequest) ProtoMessage() {}

func (x *CastStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_caster_casting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastStartRequest.ProtoReflect.Descriptor instead.
func (*CastStartRequest) Descriptor() ([]byte, []int) {
	return file_caster_casting_proto_rawDescGZIP(), []int{0}
}

func (x *CastStartRequest) GetChromecast() string {
	if x != nil {
		return x.Chromecast
	}
	return ""
}

func (x *CastStartRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type CastStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CastStartResponse) Reset() {
	*x = CastStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caster_casting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastStartResponse) ProtoMessage() {}

func (x *CastStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_caster_casting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastStartResponse.ProtoReflect.Descriptor instead.
func (*CastStartResponse) Descriptor() ([]byte, []int) {
	return file_caster_casting_proto_rawDescGZIP(), []int{1}
}

func (x *CastStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chromecast string `protobuf:"bytes,1,opt,name=chromecast,proto3" json:"chromecast,omitempty"`
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caster_casting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_caster_casting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_caster_casting_proto_rawDescGZIP(), []int{2}
}

func (x *StopStreamRequest) GetChromecast() string {
	if x != nil {
		return x.Chromecast
	}
	return ""
}

var File_caster_casting_proto protoreflect.FileDescriptor

var file_caster_casting_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x10,
	0x43, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x61, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x32, 0x90, 0x01, 0x0a,
	0x07, 0x43, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x43, 0x0a, 0x0a, 0x43, 0x61, 0x73, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x43, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a,
	0x0a, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x63, 0x61,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61,
	0x6c, 0x33, 0x30, 0x30, 0x30, 0x2f, 0x42, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65,
	0x72, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_caster_casting_proto_rawDescOnce sync.Once
	file_caster_casting_proto_rawDescData = file_caster_casting_proto_rawDesc
)

func file_caster_casting_proto_rawDescGZIP() []byte {
	file_caster_casting_proto_rawDescOnce.Do(func() {
		file_caster_casting_proto_rawDescData = protoimpl.X.CompressGZIP(file_caster_casting_proto_rawDescData)
	})
	return file_caster_casting_proto_rawDescData
}

var file_caster_casting_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_caster_casting_proto_goTypes = []interface{}{
	(*CastStartRequest)(nil),  // 0: casting.CastStartRequest
	(*CastStartResponse)(nil), // 1: casting.CastStartResponse
	(*StopStreamRequest)(nil), // 2: casting.StopStreamRequest
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_caster_casting_proto_depIdxs = []int32{
	0, // 0: casting.Casting.CastStream:input_type -> casting.CastStartRequest
	2, // 1: casting.Casting.StopStream:input_type -> casting.StopStreamRequest
	1, // 2: casting.Casting.CastStream:output_type -> casting.CastStartResponse
	3, // 3: casting.Casting.StopStream:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_caster_casting_proto_init() }
func file_caster_casting_proto_init() {
	if File_caster_casting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caster_casting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caster_casting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caster_casting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caster_casting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caster_casting_proto_goTypes,
		DependencyIndexes: file_caster_casting_proto_depIdxs,
		MessageInfos:      file_caster_casting_proto_msgTypes,
	}.Build()
	File_caster_casting_proto = out.File
	file_caster_casting_proto_rawDesc = nil
	file_caster_casting_proto_goTypes = nil
	file_caster_casting_proto_depIdxs = nil
}
