// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: caster/chromecast.proto

package caster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_FOUND Status = 0
	Status_LOST  Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "FOUND",
		1: "LOST",
	}
	Status_value = map[string]int32{
		"FOUND": 0,
		"LOST":  1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_caster_chromecast_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_caster_chromecast_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_caster_chromecast_proto_rawDescGZIP(), []int{0}
}

type FindChromecastsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChromecastName   string `protobuf:"bytes,1,opt,name=chromecastName,proto3" json:"chromecastName,omitempty"`
	ChromecastStatus Status `protobuf:"varint,2,opt,name=chromecastStatus,proto3,enum=chromecast.Status" json:"chromecastStatus,omitempty"`
}

func (x *FindChromecastsResponse) Reset() {
	*x = FindChromecastsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caster_chromecast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindChromecastsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindChromecastsResponse) ProtoMessage() {}

func (x *FindChromecastsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_caster_chromecast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindChromecastsResponse.ProtoReflect.Descriptor instead.
func (*FindChromecastsResponse) Descriptor() ([]byte, []int) {
	return file_caster_chromecast_proto_rawDescGZIP(), []int{0}
}

func (x *FindChromecastsResponse) GetChromecastName() string {
	if x != nil {
		return x.ChromecastName
	}
	return ""
}

func (x *FindChromecastsResponse) GetChromecastStatus() Status {
	if x != nil {
		return x.ChromecastStatus
	}
	return Status_FOUND
}

var File_caster_chromecast_proto protoreflect.FileDescriptor

var file_caster_chromecast_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63,
	0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x68, 0x72, 0x6f, 0x6d,
	0x65, 0x63, 0x61, 0x73, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x68, 0x72, 0x6f, 0x6d,
	0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61,
	0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x10, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65,
	0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x10, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x1d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x09, 0x0a, 0x05, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x4f, 0x53, 0x54, 0x10, 0x01, 0x32, 0x5e, 0x0a, 0x0a, 0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63,
	0x61, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x68, 0x72, 0x6f, 0x6d,
	0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x43, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x6c, 0x33, 0x30, 0x30, 0x30, 0x2f, 0x42, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_caster_chromecast_proto_rawDescOnce sync.Once
	file_caster_chromecast_proto_rawDescData = file_caster_chromecast_proto_rawDesc
)

func file_caster_chromecast_proto_rawDescGZIP() []byte {
	file_caster_chromecast_proto_rawDescOnce.Do(func() {
		file_caster_chromecast_proto_rawDescData = protoimpl.X.CompressGZIP(file_caster_chromecast_proto_rawDescData)
	})
	return file_caster_chromecast_proto_rawDescData
}

var file_caster_chromecast_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_caster_chromecast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_caster_chromecast_proto_goTypes = []interface{}{
	(Status)(0),                     // 0: chromecast.Status
	(*FindChromecastsResponse)(nil), // 1: chromecast.FindChromecastsResponse
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_caster_chromecast_proto_depIdxs = []int32{
	0, // 0: chromecast.FindChromecastsResponse.chromecastStatus:type_name -> chromecast.Status
	2, // 1: chromecast.Chromecast.FindChromecasts:input_type -> google.protobuf.Empty
	1, // 2: chromecast.Chromecast.FindChromecasts:output_type -> chromecast.FindChromecastsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_caster_chromecast_proto_init() }
func file_caster_chromecast_proto_init() {
	if File_caster_chromecast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caster_chromecast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindChromecastsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caster_chromecast_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caster_chromecast_proto_goTypes,
		DependencyIndexes: file_caster_chromecast_proto_depIdxs,
		EnumInfos:         file_caster_chromecast_proto_enumTypes,
		MessageInfos:      file_caster_chromecast_proto_msgTypes,
	}.Build()
	File_caster_chromecast_proto = out.File
	file_caster_chromecast_proto_rawDesc = nil
	file_caster_chromecast_proto_goTypes = nil
	file_caster_chromecast_proto_depIdxs = nil
}
